
# 使用最新的Docker Compose规范（无需显式声明version）
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-server
    networks:
      - app-network

  api-server:
    image: qianshe-api:0.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - "8080:8080"
    volumes:
      - api-data:/data
    networks:
      - app-network

volumes:
  api-data:
    # 定义api-data卷用于持久化数据
    driver: local

networks:
  app-network:
    # external: true # use an existing network
    driver: bridge
    name: ceremony-app-network